name: Docker Build Push
on:
  workflow_dispatch:
  push:
    branches:
      - 'feat/celo'
  pull_request:

jobs:
  Build-Container-dev:
    uses: celo-org/reusable-workflows/.github/workflows/container-cicd.yaml@v1.11.4
    if: github.ref != 'refs/heads/feat/celo'
    with:
      workload-id-provider: ${{ vars.WORKLOAD_ID_PROVIDER_NON_PROD }}
      service-account:  'safe-config-service-images-dev@devopsre.iam.gserviceaccount.com'
      artifact-registry: ${{ vars.DEV_IMAGE_REPO }}/safe-config-service
      tag: testing
      context: .
      trivy: true
  
  Build-Container:
   uses: celo-org/reusable-workflows/.github/workflows/container-cicd.yaml@v1.11.4
   if: github.ref == 'refs/heads/feat/celo'
   with:
      workload-id-provider: ${{ vars.WORKLOAD_ID_PROVIDER_PROD }}
      service-account:  'safe-config-service-images@devopsre.iam.gserviceaccount.com'
      artifact-registry: ${{ vars.SAFE_CONFIG_SERVICE_IMAGE_REPO }}/safe-config-service
      tag: latest
      context: .
      trivy: true
